//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodxClient.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodxClient.Properties.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto startup.
        /// </summary>
        internal static string AutoStartUp {
            get {
                return ResourceManager.GetString("AutoStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel.
        /// </summary>
        internal static string excel {
            get {
                return ResourceManager.GetString("excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel was not found..
        /// </summary>
        internal static string excel_Fail {
            get {
                return ResourceManager.GetString("excel.Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel has been found..
        /// </summary>
        internal static string excel_OK {
            get {
                return ResourceManager.GetString("excel.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file.
        /// </summary>
        internal static string Load_file {
            get {
                return ResourceManager.GetString("Load file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Project Application.
        /// </summary>
        internal static string msproject {
            get {
                return ResourceManager.GetString("msproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Project Application  was not found..
        /// </summary>
        internal static string msproject_Fail {
            get {
                return ResourceManager.GetString("msproject.Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Project Application  has been found..
        /// </summary>
        internal static string msproject_OK {
            get {
                return ResourceManager.GetString("msproject.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Brush.
        /// </summary>
        internal static string pbrush {
            get {
                return ResourceManager.GetString("pbrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Brush was not found..
        /// </summary>
        internal static string pbrush_Fail {
            get {
                return ResourceManager.GetString("pbrush.Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Brush has been found..
        /// </summary>
        internal static string pbrush_OK {
            get {
                return ResourceManager.GetString("pbrush.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Power Point.
        /// </summary>
        internal static string powerpnt {
            get {
                return ResourceManager.GetString("powerpnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Power Pointwas not found..
        /// </summary>
        internal static string powerpnt_Fail {
            get {
                return ResourceManager.GetString("powerpnt.Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Power Point has been found..
        /// </summary>
        internal static string powerpnt_OK {
            get {
                return ResourceManager.GetString("powerpnt.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visio.
        /// </summary>
        internal static string visio {
            get {
                return ResourceManager.GetString("visio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visio  was not found..
        /// </summary>
        internal static string visio_Fail {
            get {
                return ResourceManager.GetString("visio.Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visio  has been found..
        /// </summary>
        internal static string visio_OK {
            get {
                return ResourceManager.GetString("visio.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsof Word.
        /// </summary>
        internal static string winword {
            get {
                return ResourceManager.GetString("winword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsof Word was not found..
        /// </summary>
        internal static string winword_Fail {
            get {
                return ResourceManager.GetString("winword.Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsof Word has been found..
        /// </summary>
        internal static string winword_OK {
            get {
                return ResourceManager.GetString("winword.OK", resourceCulture);
            }
        }
    }
}
